url: https://tkavadze.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: საწყობი
email: gtkavadze@gmail.com
description: "საუკეთესო საწყობი ფართები, მობეტონებული და ადვილად მისადგომი ტერიტორია"
phone: 577 474 383

# Build settings
markdown: kramdown
permalink: pretty
