url: https://tkavadze.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: შპს " იზოლიტი"
email: tkavadze@gmail.com
description: "საუკეთესო საწყობი ფართები, მობეტონებული და ადვილად მისადგომი ტერიტორია"

header_text: ქირავდება საწყობი ფართები
phone: 599 737 847


# Build settings
markdown: kramdown
permalink: pretty

# Google services
google_analytics: UA-100113514-1
